Add manual quarantine tests
dimagi/commcare-android pull request #2396
Opened 2020-10-29 10:01 UTC by ShivamPokhriyal

2020-10-29 11:01 UTC, ShivamPokhriyal commented
Looks like it's failing because of the `changeWifi` issue in browserstack. I'll keep this PR as open, till I find a workaround for that issue.

2020-10-29 11:07 UTC, shubham1g5 commented
@ShivamPokhriyal wondering if we can add `@supress` to it so that it gets skipped on BS and then implement another annotation say "@WifiDependent" and have a mechanism to run all these wifi dependent tests locally before every release.

2020-10-29 11:14 UTC, ShivamPokhriyal commented
> @ShivamPokhriyal wondering if we can add `@supress` to it so that it gets skipped on BS and then implement another annotation say "@WifiDependent" and have a mechanism to run all these wifi dependent tests locally before every release.

Sounds really great. Will follow up on it in another PR.

2020-10-30 06:26 UTC, shubham1g5 requested changes

2020-10-30 06:26 UTC, shubham1g5 commented on app/instrumentation-tests/src/org/commcare/androidTests/ManualQuarantineTest.kt
> +        InstrumentationUtility.openModule(12)
nit: if we are using position as input to `openModule`, we should put a comment here specifiying the text of module we want to open for better readability or move the value `12` in a constant whose name indicates what module this position is for.

2020-10-30 06:26 UTC, shubham1g5 commented on app/instrumentation-tests/src/org/commcare/androidTests/ManualQuarantineTest.kt
> +        enableFormQuarantine()
we should add an additional step that just checks that you can't quarantine without this call.

2020-10-30 06:26 UTC, shubham1g5 commented on app/instrumentation-tests/src/org/commcare/androidTests/ManualQuarantineTest.kt
> +        InstrumentationUtility.changeWifi(false)
Need to suppress below Android 10

2020-11-04 10:00 UTC, ShivamPokhriyal commented
@damagatchi retest this please

2020-11-04 11:21 UTC, dimagimon commented
[![32% (0.0%) vs master 32%](https://jenkins.dimagi.com/coverage-status-icon/?coverage=0.3227&masterCoverage=0.3227)](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462111/)

2020-11-05 12:07 UTC, ShivamPokhriyal commented
@shubham1g5 Another review please.

2020-11-05 12:12 UTC, shubham1g5 approved these changes
Looks great.

2020-11-05 12:22 UTC, merged