Fix clear button styling and add click handler
dimagi/commcare-android pull request #2399
Opened 2020-11-02 10:10 UTC by ShivamPokhriyal

A follow up to #2367, where I forgot to add the click handler.

2020-11-02 10:18 UTC, shubham1g5 requested changes
code looks good, though we should add a test to test the clear button, Either robolectric or appending an existing form entry espresso test where we test for widgets should do the job.

2020-11-02 10:54 UTC, dimagimon commented
[![32% (0.0%) vs master 32%](https://jenkins.dimagi.com/coverage-status-icon/?coverage=0.3222&masterCoverage=0.3222)](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462105/)

2020-11-03 14:35 UTC, dimagimon commented
[![32% (0.0%) vs master 32%](https://jenkins.dimagi.com/coverage-status-icon/?coverage=0.3226&masterCoverage=0.3226)](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462107/)

2020-11-04 06:47 UTC, shubham1g5 approved these changes

2020-11-04 07:46 UTC, merged