Move hearbeat to use android worker
dimagi/commcare-android pull request #2423
Opened 2021-01-04 07:56 UTC by ShivamPokhriyal

Product Note: Improved heartbeat periodicity and reliability.

2021-01-05 06:45 UTC, dimagimon commented
[![32% (0.0%) vs master 32%](https://jenkins.dimagi.com/coverage-status-icon/?coverage=0.3227&masterCoverage=0.3227)](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462215/)

2021-01-05 10:55 UTC, shubham1g5 requested changes

2021-01-05 10:55 UTC, shubham1g5 commented on app/src/org/commcare/heartbeat/HeartbeatWorker.kt
> +        } catch (e: Exception) {
We should handle different network failures here like we do for other network processes like sync and updates and use Result.retry() for temporary failures.

2021-01-05 10:55 UTC, shubham1g5 commented on app/src/org/commcare/heartbeat/HeartbeatWorker.kt
> +            if (!CommCareApplication.instance().session.heartbeatSucceededForSession()) {
we should also have a `session.isActive` check here to make sure we don't fire a heartbeat after the session has expired.

2021-01-06 13:20 UTC, ShivamPokhriyal commented
@damagatchi retest this please

2021-01-06 13:50 UTC, dimagimon commented
[![32% (0.0%) vs master 32%](https://jenkins.dimagi.com/coverage-status-icon/?coverage=0.3227&masterCoverage=0.3227)](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462221/)

2021-01-07 07:47 UTC, shubham1g5 approved these changes

2021-01-12 07:05 UTC, merged