Target android 12
dimagi/commcare-android pull request #2566
Opened 2022-07-07 21:51 UTC by avazirna

## Summary
This PR adds support to Android 12 (Android SDK 31). Most of the changes are related to adding the 'exported' attribute to Activities and Receivers and setting the mutability flag of Pending Intents.  
- JIRA ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13635

## Safety Assurance

- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Test coverage
It passed all 413 Unit Tests and the results of the Instrumentation Tests were satisfactory, the results can be found [here](https://docs.google.com/document/d/14-uYpTs6K0LnLjIPiFVBFwreRwpaNDXw-Mrbs7bYkzw).

2022-07-12 10:48 UTC, avazirna commented
Test

2022-07-12 11:05 UTC, avazirna commented
@damagatchi retest this please

2022-07-12 12:22 UTC, avazirna commented
@damagatchi retest this please

2022-07-12 12:31 UTC, avazirna commented
@damagatchi retest this please

2022-07-12 12:41 UTC, avazirna commented
@damagatchi retest this please

2022-07-12 13:23 UTC, avazirna commented
@damagatchi retest this please

2022-07-12 13:37 UTC, dimagimon commented on app/src/org/commcare/CommCareNoficationManager.java
> +            PendingIntent contentIntent = PendingIntent.getActivity(context, 0, i, PendingIntent.FLAG_IMMUTABLE);
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/dimagi/commcare-android/blob/636ed8f68dcb7d308025e7f6c07ce9c3f8729d63/app/src/org/commcare/CommCareNoficationManager.java#L66"></span>Field requires API level 23 (current min is 16): <code>android.app.PendingIntent#FLAG_IMMUTABLE</code></td>
    </tr>
  </tbody>
</table>

2022-07-12 13:37 UTC, dimagimon commented on app/src/org/commcare/services/CommCareSessionService.java
> +            contentIntent = PendingIntent.getActivity(this, 0, i, PendingIntent.FLAG_UPDATE_CURRENT);
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/dimagi/commcare-android/blob/636ed8f68dcb7d308025e7f6c07ce9c3f8729d63/app/src/org/commcare/services/CommCareSessionService.java#L251"></span>Missing <code>PendingIntent</code> mutability flag</td>
    </tr>
  </tbody>
</table>

2022-07-12 13:37 UTC, dimagimon commented on app/src/org/commcare/services/CommCareSessionService.java
> +                PendingIntent contentIntent = PendingIntent.getActivity(CommCareSessionService.this, 0, callable, PendingIntent.FLAG_IMMUTABLE);
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/dimagi/commcare-android/blob/636ed8f68dcb7d308025e7f6c07ce9c3f8729d63/app/src/org/commcare/services/CommCareSessionService.java#L545"></span>Field requires API level 23 (current min is 16): <code>android.app.PendingIntent#FLAG_IMMUTABLE</code></td>
    </tr>
  </tbody>
</table>

2022-07-13 18:07 UTC, avazirna commented
@damagatchi retest this please

2022-07-13 18:12 UTC, avazirna commented
@damagatchi retest this please

2022-07-13 18:27 UTC, avazirna commented
@damagatchi retest this please

2022-07-14 04:12 UTC, shubham1g5 requested changes
@avazirna Left a few changes to address. Separately checking if you have been able to run the instrumentation tests on a Android 12 device as well ?

2022-07-14 04:12 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +            android:exported="true"
this is also used by ccc and if we decide to kill ccc should not be exported.

2022-07-14 04:12 UTC, shubham1g5 commented on app/src/org/commcare/services/CommCareSessionService.java
> +        // The FLAG_IMMUTABLE flag was added in API level 23
nit: don't think these comments are necessary as it seems evident from the sdk version check.

2022-07-15 16:17 UTC, ctsims commented on app/AndroidManifest.xml
> +            android:exported="false">
@shubham1g5 There's currently no permissioning on this activity, right?

Agreed that we should create a permission for that, but also that giving folks time to adjust and claim the permission seems important. 

Does the permission process require making a **code change** to the calling app, or does it just require the user to go manually slide the "permission granted" option in the phone settings? If the latter, I'm comfortable announcing that the next update will require the manual action on the forum. If the former, my vote for the process would be to make the export update and perform the next release, then once that release is out, immediately apply the permissions change and communicate that the next release will require claiming the permission in the calling app's code.

2022-07-15 19:52 UTC, avazirna commented
> @avazirna Left a few changes to address. Separately checking if you have been able to run the instrumentation tests on a Android 12 device as well ?

Yes, they are documented [here](https://docs.google.com/document/d/14-uYpTs6K0LnLjIPiFVBFwreRwpaNDXw-Mrbs7bYkzw/edit#heading=h.agl981v8fy8t)

2022-07-15 20:09 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:exported="false">
Closing this as no action is needed following the decision to kill CCC. I will update the documentation to reflect this decision.

2022-07-29 12:48 UTC, shubham1g5 approved these changes

2022-07-29 13:17 UTC, merged