[Reminders app] Pass on logged in user ID to data update broadcast
dimagi/commcare-android pull request #2700
Opened 2023-08-25 15:28 UTC by avazirna

## Summary
This PR includes the current user ID in the data update broadcast. The goal is to prevent CommCare users from being notified over reminders they have sent to another users. There are also changes required on the Reminders app side that are in this [PR](https://github.com/dimagi/commcare-reminders/pull/3).

## Safety Assurance

- [X] I have confidence that this PR will not introduce a regression for the reasons below

2023-10-02 21:46 UTC, avazirna commented
@damagatchi retest this please

2023-10-04 03:58 UTC, shubham1g5 requested changes

2023-10-04 07:59 UTC, avazirna commented
@shubham1g5 these comments were not visible to me, were they pending still on your end?

2023-10-04 13:30 UTC, shubham1g5 approved these changes

2023-10-04 14:26 UTC, merged