biometric design changes
dimagi/commcare-android pull request #2770
Opened 2024-06-24 21:31 UTC by pm-dimagi

## Summary
Remove extra page of biometric implemented the new design for the same
Tickets
https://dimagi.atlassian.net/browse/CCCT-349
https://dimagi.atlassian.net/browse/CCCT-355
https://dimagi.atlassian.net/browse/CCCT-356

## Feature Flag

## Product Description

## Safety Assurance

- [ ] If the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

### Safety story

2024-07-17 18:39 UTC, OrangeAndGreen requested changes
Summarizing some main themes from the comments:
1. The allowPassword stuff in biometric config is gone on purpose, so that code can go away
2. Some confusion in the behavior when user needs to configure fingerprint/PIN
3. CONNECT_UNLOCK_BIOMETRIC and ConnectIdBiometricUnlockActivity should both be going away

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/BiometricSignupPage.java
Let's stash this new page for now and bring it back in another PR once we're ready for the UI changes (coming soon).

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/BiometricSignupPageUiController.java
Likewise, stash until later

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/res/values/strings.xml
> +    <string name="app_lock">App Lock</string>
Looks like some/all of these can be stashed until we bring in the new BiometricSignupPage?

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> +        allowPassword = getIntent().hasExtra(ConnectConstants.ALLOW_PASSWORD) && getIntent().getStringExtra(ConnectConstants.ALLOW_PASSWORD).equals("true");;
This is no longer an option since recovery passwords are deprecated, we can get rid of allowPassword and any related functionality.

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> -            finish(true, true);
This line should stay. This handles the rare case where the user's device doesn't support PIN or fingerprint for screen unlock. When that happens this activity should exit out, and ConnectIdWorkflows then shows a message indicating that the user can not use this device with ConnectID.

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> +        if (BiometricsHelper.isFingerprintConfigured(this, biometricManager)) {
This logic should only handle fingerprint. Also, it needs to call BiometricsHelper.configureFingerprint if the fingerprint isn't configured yet (that function sends the user to the Android fingerprint config).

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> -    public void handlePinButton() {
We still need this function to handle configuring or proceeding with the PIN

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivityUiController.java
> +//        pinButton.setOnClickListener(v -> activity.handlePinButton());
We still need this button handler for when the user wants to (possibly) configure and proceed using a PIN as their screen unlock.

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> -    public void handlePinButton() {
See above comment related to fingerprint for more info.

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> +    public void performPasswordUnlock() {
Obsolete

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdBiometricConfigActivity.java
> +                        performPasswordUnlock();
No password fallback anymore, at this point the user needs to recover their account

2024-07-17 18:39 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectIdWorkflows.java
>              case CONNECT_UNLOCK_BIOMETRIC -> {
Looks like this task should go as well. It's the last one linking to ConnectIdBiometricUnlockActivity. Anywhere that used this should perform the unlock directly instead, and once this is gone we can also get rid of the obsolete activity.

2025-04-09 10:42 UTC, shubham1g5 commented
@pm-dimagi Curious what happened here, the PR is not merge but the related ticets are marked as done. Do we need this PR to be merged or this can be closed ?

2025-04-09 12:02 UTC, pm-dimagi commented
@shubham1g5 this pr can be closed as changes related to this are already in qa branch and some changes are skipped so we can close this

2025-04-09 12:28 UTC, closed without merging