Pm ccct 415 - Nav Graph implementation
dimagi/commcare-android pull request #2819
Opened 2024-08-16 20:25 UTC by pm-dimagi

Complete nav graph implementation with data binding
## Feature Flag

Nav GRaph

## Safety Assurance

- [ ] If the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

### Safety story

2024-08-28 15:58 UTC, OrangeAndGreen requested changes
I reviewed everything except the new fragments (i.e. fragments/connectId folder). I'll return to that but left comments to start addressing in the meantime.

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/CommCareSetupActivity.java
> +    private BiometricManager biometricManager;
This code should be encapsulated elsewhere so it isn't directly in this activity, more thoughts in comments below

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/CommCareSetupActivity.java
> +        biometricManager = BiometricManager.from(this);
Encapsulate into BiometricsHelper method when Connect button pressed

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/CommCareSetupActivity.java
> +        return new BiometricPrompt.AuthenticationCallback() {
Pass these callbacks into the new BiometricsHelper method as an anonymous AuthenticationCallback

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/CommCareSetupActivity.java
> +        if(requestCode== ConnectConstants.CONNECT_UNLOCK_PIN){
Move these cases into a BiometricsHelper.onActivityResult(int, int, Intent) function

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/CommCareSetupActivity.java
> +            case ConnectManager.CONNECTID_REQUEST_CODE :
This should be handled via ConnectManager.handleFinishedActivity instead (called in the default case of this switch)

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/LoginActivity.java
> +    private BiometricManager biometricManager;
Similar concerns here to CommCareSetupActivity, about encapsulation an repeating code related to unlocking ConnectID

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +    static NavDirections navDirections = null;
This can be changed to a local variable in each of the functions where it's used, no need to hang on to it long-term

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +        if(requestCode==ConnectManager.CONNECTID_REQUEST_CODE){
"else if"

Also seems strange that this constant is defined in ConnectManager instead of ConnectConstants like the one above.

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +        switch (value){
Move this switch into the if structure above

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +//    @Override
Delete commented code

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +                    navDirections = org.commcare.fragments.connectId.ConnectIdRecoveryDecisionFragmentDirections.actionConnectidRecoveryDecisionToConnectidPin(ConnectConstants.CONNECT_UNLOCK_PIN, use
Import ConnectIdRecoveryDecisionFragmentDirections in the file to simplify these statements

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +    public static void beginRegistration1(Context parent) {
Remove "1" at end of function name

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +        if (requestCode != ConnectConstants.CONNECT_NO_ACTIVITY) {
Flip this to simplify the logic and only call navigate() once, i.e.:
```
if(NO_ACTIVITY) {
   navDirections = ...RecoveryDecisionSelf
}

if(navDirections != null) {
   navigate(...)
}
```

But looking more closely, what is the navigating back to self thing for?

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +                    navDirections = org.commcare.fragments.connectId.ConnectIdRecoveryDecisionFragmentDirections.actionConnectidRecoveryDecisionToConnectidPin(ConnectConstants.CONNECT_UNLOCK_PIN, use
Seem like it shouldn't be necessary to pass CONNECT_UNLOCK_PIN into a method that says we're navigating to Pin

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +                    navDirections = org.commcare.fragments.connectId.ConnectIdRecoveryDecisionFragmentDirections.actionConnectidRecoveryDecisionToConnectidPassword(ConnectConstants.CONNECT_UNLOCK_PAS
Similar to Pin, if we're navigating to actionConnectidRecoveryDecisionToConnectidPassword why do we have to pass in CONNECT_UNLOCK_PASSWORD as well?

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/connect/ConnectIdActivity.java
> +        navDirections = org.commcare.fragments.connectId.ConnectIdRecoveryDecisionFragmentDirections.actionConnectidRecoveryDecisionToConnectidMessage(parent.getString(R.string.connect_recovery_alt_t
Add some newlines to break this line up and make it more readable, like before each call to parent.getString()

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectConstants.java
> +    public final  static int CONNECT_NO_ACTIVITY=ConnectConstants.ConnectIdTaskIdOffset + 1;
Looks like a bunch of extra spaces in these lines between final and static. Easy to clean up with the help of the Alt key!

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +    public static final int CONNECTID_REQUEST_CODE = 1034;
Move this to ConnectConstants with the other request codes

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +    public static void launchConnectId(Context context){
Not used, delete

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +    private static ConnectIdStatus connectStatus = ConnectIdStatus.NotIntroduced;
This shouldn't be static, can be accessed through the singleton instead, i.e. getInstance().connectStatus

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
>      private ConnectActivityCompleteListener loginListener;
Looks like this isn't used anymore? If that's correct it should be deleted

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> -        scheduleHearbeat();
Looks like these two lines never get called now, but they still need to be called somewhere

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectConstants.java
> +    public static final String BIGIN_REGISTRATION = "BIGIN_REGISTRATION";
Typo: BIGIN instead of BEGIN

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> -        if(instance.loginListener != null) {
If this is no longer necessary then CommCareSetupActivity shouldn't be passing in a callback handler

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +            intent.putExtra("TASK",ConnectConstants.UNLOCK_CONNECT);
Let's create a common launchConnectId(parent, ConnectConstants task) function so we don't have to repeat the details of the intent (like "TASK")

2024-08-28 15:58 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +//            ConnectIdActivity.unlockConnect(parent, success -> {
Delete commented code

2024-08-29 18:41 UTC, pm-dimagi commented on app/res/layout/screen_connect.xml
> -        app:defaultNavHost="true"
yes

2024-09-03 21:58 UTC, OrangeAndGreen approved these changes

2024-09-03 21:58 UTC, merged