CCCT-470 || Country-Code Phone Edittext UI
dimagi/commcare-android pull request #2830
Opened 2024-08-27 10:27 UTC by j13panchal

## Summary
https://dimagi.atlassian.net/browse/CCCT-470

## Feature Flag

## Product Description

## Safety Assurance

- [ ] If the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

### Safety story

2024-08-28 16:17 UTC, OrangeAndGreen requested changes
See the comment about change to the manifest, but otherwise everything looks great!

2024-08-28 16:17 UTC, OrangeAndGreen commented on app/AndroidManifest.xml
Per feedback from the other mobile devs, we should avoid doing these large reorganizations as part of other PRs. Let's back this one up so it only has any required changes. We can also do the organizational refactor over on the master branch and create a PR for it there, then pull the change up to our branch once it's accepted in master.

2024-09-02 06:04 UTC, j13panchal commented on app/AndroidManifest.xml
I revert all reorganizations code from Manifest file

2024-09-03 12:23 UTC, OrangeAndGreen approved these changes

2024-09-03 12:23 UTC, merged