Quarantine forms due to malformed xml as unrecoverable
dimagi/commcare-android pull request #2859
Opened 2024-09-18 22:57 UTC by avazirna

## Summary
This PR adds a new `SaveStatus`, `SAVE_UNRECOVERABLE_ERROR`, to be used when quarantining forms due to malformed or corrupted form XML. These forms can't be added to the submissions queue to be resent. All other form processing errors are quarantined as `RECORD_ERROR`.

## Safety Assurance

- [X] If the PR is high risk, "High Risk" label is set
- [X] I have confidence that this PR will not introduce a regression for the reasons below
- [X] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Safety story

2024-09-18 23:05 UTC, avazirna commented
@damagatchi retest this please

2024-09-19 04:25 UTC, shubham1g5 requested changes
Safety story should detail out the testing performed for this change.

2024-09-19 04:25 UTC, shubham1g5 commented on app/src/org/commcare/tasks/SaveToDiskTask.java
> +            return new ResultAndError<>(SaveStatus.SAVE_UNRECOVERABLE_ERROR, cleanedMessage);
think all the places where we are throwing `SaveStatus.SAVE_ERROR` above should be `SaveStatus.SAVE_UNRECOVERABLE_ERROR` with this change.

2024-09-19 04:25 UTC, shubham1g5 commented on app/src/org/commcare/tasks/SaveToDiskTask.java
> +            return new ResultAndError<>(SaveStatus.SAVE_UNRECOVERABLE_ERROR, cleanedMessage);
Also would you be able to provide more details around the error pathway you think the [crash linked in the PR](https://github.com/dimagi/commcare-android/pull/2803) will surface as in this method.

2024-09-19 11:23 UTC, avazirna commented
> Safety story should detail out the testing performed for this change.

hi @shubham1g5 I have added more details to the description of the PR, including the way I tested the changes.

2024-09-19 12:34 UTC, shubham1g5 commented
> Those quarantined due to RuntimeException were then sent back to the queue and submitted to HQ

Where exactly in code are we quarantining the forms erroring due to `RuntimeException` ?

2024-09-19 15:36 UTC, avazirna commented
> > Those quarantined due to RuntimeException were then sent back to the queue and submitted to HQ
> 
> Where exactly in code are we quarantining the forms erroring due to `RuntimeException` ?

[Here](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/activities/FormEntryActivity.java#L1312), based on the `SaveStatus` we decide the quarantine reason, QuarantineReason_LOCAL_PROCESSING_ERROR for unrecoverable errors and QuarantineReason_RECORD_ERROR otherwise.

2024-09-19 18:16 UTC, shubham1g5 commented
> [Here](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/activities/FormEntryActivity.java#L1312), based on the SaveStatus we decide the quarantine reason, QuarantineReason_LOCAL_PROCESSING_ERROR for unrecoverable errors and QuarantineReason_RECORD_ERROR otherwise.

@avazirna  How is that related to `RuntimeException` or how does `RuntimeException` gets represented as `SAVE_ERROR` or  `SAVE_UNRECOVERABLE_ERROR`

2024-09-19 19:15 UTC, avazirna commented
> @avazirna How is that related to `RuntimeException` or how does `RuntimeException` gets represented as `SAVE_ERROR` or `SAVE_UNRECOVERABLE_ERROR` ?

Using the [same method where the NPE was thrown](https://github.com/dimagi/commcare-android/blob/5a0578a7ee045c61cd26c6511d4a6696be6f9941/app/src/org/commcare/models/FormRecordProcessor.java#L66), the exception is caught by [this generic catch](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/android/database/user/models/FormRecord.java#L406) which then wraps the exception in a `RuntimeException` that is then caught by this [other generic catch](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/android/database/user/models/FormRecord.java#L348), this is then [wrapped in a SQLException](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/android/database/user/models/FormRecord.java#L351) that bubbles all the way up until [CommCareTask.doInBackground()](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/tasks/templates/CommCareTask.java#L37). There is gets caught by [this catch clause](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/tasks/templates/CommCareTask.java#L41) and returns `null`. With the result `null`, [onPostExecute](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/tasks/SaveToDiskTask.java#L268) saves the [form with SaveStatus.SAVE_ERROR](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/tasks/SaveToDiskTask.java#L274).

2024-09-20 08:21 UTC, shubham1g5 approved these changes
Thanks for the detailed explanation.

2024-09-20 08:21 UTC, shubham1g5 commented on app/src/org/commcare/activities/FormEntryActivity.java
> +                            : QuarantineReason_RECORD_ERROR ;
nit:formatting

2024-09-20 14:17 UTC, avazirna commented
@damagatchi retest this please

2024-09-20 16:14 UTC, merged