CCCT-533- ui icon changes as per the new figma
dimagi/commcare-android pull request #2892
Opened 2024-11-11 19:29 UTC by pm-dimagi

https://dimagi.atlassian.net/browse/CCCT-533

The ui changes 
-- Icon update
-- commcare logo update 

## Safety Assurance

- [ ] If the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

### Safety story
 

Release Note: Updated Iconography and Logo

2024-11-12 05:15 UTC, shubham1g5 requested changes
The code changes looks fine. 

1. Is it possible to add screenshots in the PR on how it looks in the app ?
2. Is it possible to use vector drawables insted of png to take into account different screen densities.

2024-11-12 06:06 UTC, pm-dimagi commented
![WhatsApp Image 2024-11-12 at 11 34 50 (1)](https://github.com/user-attachments/assets/292e7a9e-15c2-4196-a7c4-0f134a73b143)
![WhatsApp Image 2024-11-12 at 11 34 50 (2)](https://github.com/user-attachments/assets/d1be1d9a-39f3-4262-88e0-8525ca847a3a)
![WhatsApp Image 2024-11-12 at 11 34 50](https://github.com/user-attachments/assets/6c8cc347-2580-4411-b7cb-00a6440ebc11)

2024-11-12 08:10 UTC, avazirna reviewed
@pm-dimagi can you include a screenshot of the full Home screen, with the `Incomplete` and `Saved` buttons?
<img src="https://github.com/user-attachments/assets/a015aba4-5ae5-4f65-8c67-966005b569fd" width="150px"/>

2024-11-12 09:19 UTC, pm-dimagi commented on app/res/layout/install_confirm_fragment.xml
> +                                SquareButtonWithText:img="@drawable/download"
I was not aware of its usage at other places so i kept the old one and added the new ones

2024-11-13 15:30 UTC, shubham1g5 approved these changes
Changes looks good to me. It's a good idea to add a release note to any big changes like this and also tick the safety checklist in PR template.

2024-11-14 10:59 UTC, avazirna approved these changes

2024-11-14 11:00 UTC, avazirna commented
@damagatchi retest this please

2024-11-14 16:18 UTC, kcowger commented
@pm-dimagi I'm seeing a different design (different icons, different icon sizes) on the final assets provided to SaaS here: https://www.figma.com/design/UWjp1wRNAO0o9q2llwDKMc/CommCare-Cosmetic-Changes-Post-Nov-'22Rebrand?node-id=111-2&node-type=canvas

Can you confirm where you got these icons and icon sizes? I want to make sure we are working on off of the same assets.

2024-11-19 03:59 UTC, pm-dimagi commented
@kcowger i downloaded the assets from the figma file only not got any icon sizes
I got this figma file for refrence https://www.figma.com/design/UWjp1wRNAO0o9q2llwDKMc/CommCare-Cosmetic-Changes-Post-Nov-'22Rebrand?node-id=625-2&node-type=canvas&t=ijXRvUyGF2lRrV6G-0

2024-11-20 05:24 UTC, shubham1g5 approved these changes
Changes looks good, but tests seems to be failing - 

````
org.commcare.android.tests.application.AppUpdateTest > testAppUpdate FAILED
21:09:01     java.lang.ExceptionInInitializerError at AppUpdateTest.kt:197
21:09:01         Caused by: java.lang.IllegalStateException at AppUpdateTest.kt:197
21:09:01 
21:09:01 org.commcare.android.tests.application.AppUpdateTest > testUpdateToBrokenApp FAILED
21:09:01     java.lang.NoClassDefFoundError at AppUpdateTest.kt:197
21:09:02 
21:09:02 org.commcare.android.tests.application.AppUpdateTest > testAppIsUpToDate FAILED
21:09:02     java.lang.NoClassDefFoundError at AppUpdateTest.kt:197
21:09:03 
21:09:03 org.commcare.android.tests.application.AppUpdateTest > testAppUpdateWithSuiteFixture FAILED
21:09:03     java.lang.NoClassDefFoundError at AppUpdateTest.kt:197
21:09:03 
21:09:03 org.commcare.android.tests.application.AppUpdateTest > testUpdateToAppWithIncompatibleVersion FAILED
21:09:03     java.lang.NoClassDefFoundError at AppUpdateTest.kt:197
21:09:04 
21:09:04 org.commcare.android.tests.application.AppUpdateTest > testUpdateToAppWithMultimedia FAILED
21:09:04     java.lang.NoClassDefFoundError at AppUpdateTest.kt:197
````

2024-11-20 12:57 UTC, avazirna commented
>  some revamp in colors

@pm-dimagi from this screenshot, it seems that the app bar colour was not updated according with the new design, will that be address in a separate PR?

2024-11-20 14:01 UTC, pm-dimagi commented
Yess

On Wed, 20 Nov, 2024, 6:28 pm Ahmad Treptt Vazirna, <
***@***.***> wrote:

> some revamp in colors
>
> @pm-dimagi <https://github.com/pm-dimagi> from this screenshot, it seems
> that the app bar colour was not updated according with the new design, will
> that be address in a separate PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dimagi/commcare-android/pull/2892#issuecomment-2488518203>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BI42OB56IT443K7YRZGYXLL2BSBN5AVCNFSM6AAAAABRSPSVSGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBYGUYTQMRQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-20 16:04 UTC, pm-dimagi commented
@damagatchi please retest this

2024-11-20 16:04 UTC, OrangeAndGreen commented
@damagatchi retest this please

2024-11-20 19:02 UTC, OrangeAndGreen approved these changes

2024-11-20 19:26 UTC, pm-dimagi commented
@damagatchi retest this please

2024-11-20 19:44 UTC, pm-dimagi commented
@damagatchi retest this please

2024-11-20 20:35 UTC, merged

2024-11-28 13:41 UTC, shubham1g5 commented
@pm-dimagi FYI that In your last screenshot, the text on the log out button is getting cut off.