CCCT-467 || User Payment Info
dimagi/commcare-android pull request #2912
Opened 2024-12-09 13:59 UTC by j13panchal

## Summary
https://dimagi.atlassian.net/browse/CCCT-467

## Feature Flag

## Product Description

## PR Checklist

- [ ] If I think the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly
- [ ] Does the PR introduce any major changes worth communicating ? If yes, "Release Note" label is set and a "Release Note" is specified in PR description.

### Automated test coverage

### Safety story

2025-01-08 10:11 UTC, shubham1g5 commented
@j13panchal Can we make sure to populate PR template abundantly here with all details that you think can make life easy for a reviewer including screenshots for any UI/xml changes. Thanks!

2025-01-21 17:27 UTC, OrangeAndGreen commented on app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
> +        this.paymentPhone = paymentPhone;
Adding the NotNull annotation to all inputs for the constructor. Empty strings are okay for when the information hasn't been specified by the user yet.

2025-01-21 17:27 UTC, OrangeAndGreen commented on app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
> +
Adding javadoc comments for all fields

2025-01-21 17:29 UTC, OrangeAndGreen commented on app/src/org/commcare/fragments/connect/ConnectPaymentSetupFragment.java
> +                        }
Changing this to log the exception then fail silently. This is only a helper to auto-populate the user's phone number, if it doesn't work they can still type the number in manually and proceed.

2025-01-21 18:18 UTC, OrangeAndGreen commented on app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
> +                                    password, name, "",paymentName,paymentPhone);
It's okay if the response from the server doesn't include payment info, we just put blank strings in the DB instead.

2025-02-25 16:28 UTC, shubham1g5 requested changes

2025-02-25 16:28 UTC, shubham1g5 commented on app/src/org/commcare/fragments/connect/ConnectPaymentSetupFragment.java
> +        binding.countryCode.addTextChangedListener(new TextWatcher() {
code formatting is off

2025-02-25 16:28 UTC, shubham1g5 commented on app/src/org/commcare/fragments/connect/ConnectPaymentSetupFragment.java
> +public class ConnectPaymentSetupFragment extends Fragment {
There seems to be code in this class which is quite similar to some other connect classes around phone number handling. We need to try very hard to not repeat such blocks of code in the codebase as much as possible.

2025-05-14 17:08 UTC, closed without merging