CCCT-567 || Home Screen UI Fixes
dimagi/commcare-android pull request #2917
Opened 2024-12-11 11:45 UTC by j13panchal

## Summary
https://dimagi.atlassian.net/browse/CCCT-567

## Feature Flag

## Product Description

## PR Checklist

- [ ] If I think the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly
- [ ] Does the PR introduce any major changes worth communicating ? If yes, "Release Note" label is set and a "Release Note" is specified in PR description.

### Automated test coverage

### Safety story

2024-12-11 19:35 UTC, OrangeAndGreen requested changes

2024-12-11 19:35 UTC, OrangeAndGreen commented on app/src/org/commcare/activities/HomeButtons.java
> -    private final static String[] buttonNames =
Apologies, I should have provided more guidance here. Hiding the button can be accomplished more easily and without having to make additional modifications to this code. Instead, we just need to enhance StandardHomeActivityUIController.getHiddenButtons so it correctly indicates when to hide the Job Status button. The list of button names returned by that function is passed through to HomeButtons so buttons can be shown or hidden as indicated.

2024-12-11 19:35 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +    public static boolean shouldShowJobStatus(Activity activity) {
StandardHomeActivityUIController.getHiddenButtons an call this method to determine whether to add "connect" to the list of hidden buttons.

2024-12-11 19:35 UTC, OrangeAndGreen commented on app/src/org/commcare/connect/ConnectManager.java
> +        return job.getStatus() == STATUS_DELIVERING && record.getIsLearning();
For the logic here, we want to check for two possibilities where we want to show the Job Status button:
1. Job in learning state, logged in to learning app
2. Job in delivery state, logged in to delivery app

So (status == LEARNING && record.getIsLearning) || (status == DELIVERY && !record.getisLearning)

2024-12-12 05:02 UTC, shubham1g5 commented
(Testing code rabbit here)
@coderabbitai full review please

2024-12-12 15:08 UTC, OrangeAndGreen approved these changes

2024-12-12 15:08 UTC, merged