Primes Entity cache ahead of time
dimagi/commcare-android pull request #2928
Opened 2024-12-19 11:07 UTC by shubham1g5

## Summary

Uses a Work manager task to schedule entity list cache calculation ahead of time. 

## Feature Flag

CACHE_AND_INDEX

## PR Checklist

- [ ] If I think the PR is high risk, "High Risk" label is set
- [ ] I have confidence that this PR will not introduce a regression for the reasons below
- [ ] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly
- [ ] Does the PR introduce any major changes worth communicating ? If yes, "Release Note" label is set and a "Release Note" is specified in PR description.

### Automated test coverage

### Safety story

2024-12-25 10:53 UTC, shubham1g5 commented
@codereabbitai full review

2024-12-26 11:12 UTC, shubham1g5 commented on app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
> +    }
This code is only ever invoked from a background thread. Is there a way I can be explicit about that ?

2024-12-26 11:20 UTC, shubham1g5 commented on app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
> +    }
avoiding to do this for now as the code is shared with CLI which will actually calls this on main thread.

2025-01-10 08:38 UTC, shubham1g5 commented
@coderabbitai full review please

2025-01-17 23:37 UTC, ctsims requested changes
Mostly minor feedback, but I think the issues raised with the Singleton pattern for the caching helper need to be addressed. I think it can be implemented without creating a new independent static lifecycle, and that we should be trying to avoid needing new static lifecycles in the future if possible, especially for classes that could be executing independent working code outside of the managed app lifecycle.

2025-01-17 23:37 UTC, ctsims commented on app/src/org/commcare/activities/EntitySelectActivity.java
> -        if (shortSelect.shouldBeLaidOutInGrid()) {
Is this removing the gridview modality of entity selects entirely? I think it is mostly deprecated, but probably important to call out specifically if so to confirm that it's safe to do so.

2025-01-17 23:37 UTC, ctsims commented on app/src/org/commcare/activities/EntitySelectActivity.java
> +        setProgressText(StringUtils.getStringRobust(this, R.string.entity_list_finalizing));
This message doesn't seem like the right one to me. Isn't this just the start of the loading process?

2025-01-17 23:37 UTC, ctsims commented on app/src/org/commcare/activities/EntitySelectActivity.java
> +                        StringUtils.getStringRobust(this, R.string.entity_list_processing,
Raw count text inside the view might be a tricky way to view this progress, btw, compared to another form of loading indicator. 

In the big views we've used with cache and index historically, sometimes the length of the view is tens-of-thousands of cases, which is going to make a fairly large and pretty messy looking view. Even just using a % might work better.

2025-01-17 23:37 UTC, ctsims commented on app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
> +        if (detail.shouldOptimize() && detail.isCacheEnabled) {
There was another place where a similar check was done, which implied there were 3 potential states for this system based on combinations of different configs. I'm a little concerned it'll be hard to the various places these modes are checked in sync over time, it might be helpful to unify the checks in one place so that if changes are made later we can't miss one.

2025-01-17 23:37 UTC, ctsims commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +            primeEntityCacheForApp(CommCareApplication.instance().commCarePlatform)
I'd be worried managing the parts of the lifecycle here that depend on the current state of the seated application and platform implicitly. I think it's going to be really hard to ensure aligned execution with the app state resources (for example, an app being unseated and a different app being reseated in between calls without a bad read happening in between that kills the worker). 

There are a couple of ways to control for that, but I think the safest might be to make access to the helper/worker come from a different object's lifecycle, like nesting it inside the currently seated application/platform singleton and then associating that helper with the public call, rather than making this helper itself the singleton object. That would make sure that if there was misalignment, it would stay limited to the orphaned helper.

2025-01-22 09:35 UTC, shubham1g5 commented on app/src/org/commcare/activities/EntitySelectActivity.java
> -        if (shortSelect.shouldBeLaidOutInGrid()) {
No, the intention here was to remove duplicattion with [setupUI()](https://github.com/dimagi/commcare-android/blob/dbbcfd48c9a5e7ddc447b494b5d8598e4abf1db8/app/src/org/commcare/activities/EntitySelectActivity.java#L262.) which gets called in Activity's `onCreate`

2025-01-23 13:56 UTC, shubham1g5 commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +            primeEntityCacheForApp(CommCareApplication.instance().commCarePlatform)
> to make access to the helper/worker come from a different object's lifecycle, like nesting it inside the currently seated application/platform singleton and then associating that helper with the public call, rather than making this helper itself the singleton object.

Would not that mean that there can be multiple instances of the `PrimeEntityCacheHelper`  per application singleton ? I think we also want to make sure that we don't duplicate cache priming work in simultaneous threads.

2025-01-24 23:07 UTC, ctsims commented on app/src/org/commcare/activities/EntitySelectActivity.java
> -        if (shortSelect.shouldBeLaidOutInGrid()) {
aha, got it. I didn't see that code duplicated elsewhere so I assumed it was removed for being old/broken. Thanks for clarifying

2025-01-24 23:24 UTC, ctsims commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +            primeEntityCacheForApp(CommCareApplication.instance().commCarePlatform)
If we make it a member of the seated singleton platform/app there will only ever be one helper per seated application, but it means that it's much easier to tie lifecycle events to the application itself, since we could make the app platform object final and immutable. 

Specifically, it would let us be sure that in the process of unseating one app and seating another that neither of those objects could end up with a state mismatch. If the currently seated storage changed underneath the one shutting down, it would fail and could close itself out naturally, and the new one spinning up wouldn't have to deal with things like race conditions in the process of closing out old listeners while other ones are being added.

2025-02-04 08:55 UTC, shubham1g5 commented on app/src/org/commcare/activities/EntitySelectActivity.java
> +                        StringUtils.getStringRobust(this, R.string.entity_list_processing,
https://github.com/dimagi/commcare-android/pull/2928/commits/15cf20ad67bc7290a2ef6502acf2d70049244def

2025-02-04 08:55 UTC, shubham1g5 commented on app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
> +        if (detail.shouldOptimize() && detail.isCacheEnabled) {
https://github.com/dimagi/commcare-android/pull/2928/commits/71981614565917191d1fe077982d9633cbc31411

2025-02-04 08:56 UTC, shubham1g5 commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +            primeEntityCacheForApp(CommCareApplication.instance().commCarePlatform)
https://github.com/dimagi/commcare-android/pull/2928/commits/aa65ba4f9db4e58cb1d4838cd3c0dc650b89105f, not completely sure if this is what you meant though.

2025-02-04 09:07 UTC, shubham1g5 commented on app/src/org/commcare/activities/EntitySelectActivity.java
> +        setProgressText(StringUtils.getStringRobust(this, R.string.entity_list_finalizing));
changes the message to `soting cases` in https://github.com/dimagi/commcare-android/pull/2928/commits/b24d5800ccee08fcaf272ecf7f55dd12e20586d8 as I think that will be the most time consuming process after setting the adapter. We do things differently based on different configs mode which makes it hard to deduce the right message for different phases but below is a gist to make it more clear - 

1. Normal Entity List (without caching and lazy loading)

- We calculate the entity references and calculate all Entity Fields simultaneously
- Set the List to Adapter which in turn also sorts the list using already calculated fields


2. With Cache Enabled but no lazy loading

- We calculate the async entity references from nodeset
- Subsequently, We calculate all entity fields which can happen from cache or a raw xpath calculation 
- Set the List to Adapter which in turn also sorts the list using already calculated fields


3. With Cache and Lazy Loading Enabled

- We calculate the async entity references from nodeset
- We calculate All NON-OPTIMIZABLE entity fields
- Set the List to Adapter which in turn also sorts the list (We may need to calculate any lazy fields here if sorting is specified on the lazy field)
- We calculate Optimzed fields lazily and cache them as user scroll through the list


In all of these scenarios, the only major thing between setting the list to adapter and user seeing cases on the list is "Sorting" which is why I have now changed this message to signify that.

2025-02-27 00:05 UTC, ctsims commented on app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
> +            throw RuntimeException(AndroidAsyncNodeEntityFactory::class.simpleName + " can only be used for optimizable case lists");
Great change, this is  really solid refactor.

2025-02-27 00:06 UTC, ctsims commented on app/src/org/commcare/CommCareApp.java
> +    public PrimeEntityCacheHelper getPrimeEntityCacheHelper() {
Thanks for the refactor, I think this coupling will make a lot of sense and keep things straight

2025-02-27 00:08 UTC, ctsims commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +        WorkManager.getInstance(CommCareApplication.instance()).cancelUniqueWork(PRIME_ENTITY_CACHE_REQUEST)
No need to address if I'm overthinking, but if the spin-down process for this getting executed takes some time, will it already be out of the queue reliably by the next worker? If not, should this be keyed against something like the app id / work type as well? It's probably a non-issue since an old worker will error out anyway when its database goes away.

2025-02-27 00:13 UTC, ctsims commented on app/res/values/strings.xml
> +    <string name="entity_list_sorting" cc:translatable="true">Sorting cases…</string>
Very nit-picky feedback - I don't know that 'sorting' here adds a lot of detail for users and might be a little tricky to translate, but "Finalizing" is also extremely technical, so I also wouldn't recommend switching back. I wonder if 'Finishing' might be a good, less jargon-y way to communicate.

2025-02-27 00:15 UTC, ctsims approved these changes
Re-reviewed commit by commit and I think my core feedback was all addressed. Only remaining input is that it'd be really great to get how this works written down somewhere, and make sure that the underlying states are communicated effectively for debugging. There are now a lot of factors involved in how things get processed.

2025-02-27 11:00 UTC, shubham1g5 commented on app/res/values/strings.xml
> +    <string name="entity_list_sorting" cc:translatable="true">Sorting cases…</string>
https://github.com/dimagi/commcare-android/pull/2928/commits/7530f944acd849ac4731affdb3bb128768fabf2a

2025-02-27 11:01 UTC, shubham1g5 commented on app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
> +        WorkManager.getInstance(CommCareApplication.instance()).cancelUniqueWork(PRIME_ENTITY_CACHE_REQUEST)
I would think so but probably better to not rely on assumptions and also it's more consistent with other app specific requests - https://github.com/dimagi/commcare-android/pull/2928/commits/99329d3292b941081cdead072fe559e9c193076e and https://github.com/dimagi/commcare-android/pull/2928/commits/89a054f50ac7a00baa2ed69d02d6a9592f1ef0e0

2025-02-27 11:05 UTC, shubham1g5 commented
> Only remaining input is that it'd be really great to get how this works written down somewhere, and make sure that the underlying states are communicated effectively for debugging.

That resonates with me. I will prioritize a wiki here and get back on it.

2025-02-27 11:11 UTC, shubham1g5 commented
@coderabbitai generate docstrings

2025-02-27 11:12 UTC, shubham1g5 commented
@damagatchi retest this please

2025-03-03 22:36 UTC, ctsims commented
> Also curious if you have opinion on this level of details in Java docs - https://github.com/dimagi/commcare-android/pull/2965 ?

Hm.. I feel like that level of docstring is somewhat anti-useful. Since it's pulling the docs from the method signatures I think it's just replicating the information already there without adding value, while introducing risk that someone only changes one source and not the other

2025-03-03 22:36 UTC, ctsims approved these changes

2025-03-04 02:54 UTC, shubham1g5 commented
@damagatchi retest this please

2025-03-04 11:12 UTC, avazirna approved these changes

2025-03-04 11:17 UTC, merged