Update components exported attribute
dimagi/commcare-android pull request #2930
Opened 2024-12-20 21:46 UTC by avazirna

## Summary
Ticket: https://dimagi.atlassian.net/browse/QA-7356

## PR Checklist

- [X] If I think the PR is high risk, "High Risk" label is set
- [X] I have confidence that this PR will not introduce a regression for the reasons below
- [X] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly
- [X] Does the PR introduce any major changes worth communicating ? If yes, "Release Note" label is set and a "Release Note" is specified in PR description.

2024-12-24 08:55 UTC, shubham1g5 commented
@avazirna can you link the Android docs reg. restriction you are talking about in PR description.

2024-12-26 10:59 UTC, avazirna commented
> @avazirna can you link the Android docs reg. restriction you are talking about in PR description.

done @shubham1g5, we might need to consider having an option to allow app callout questions to use explicit intents.

2024-12-30 06:39 UTC, shubham1g5 commented
@avazirna I think we need to implement a permission at the very least for these exported components as we don't really want to allow other apps to have access to these.

2025-01-08 14:35 UTC, avazirna commented
@coderabbitai review

2025-01-09 07:33 UTC, shubham1g5 requested changes

2025-01-09 07:33 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +        android:name="${applicationId}.permission.READ_NFC_DATA"
@avazirna Here the permission `READ_NFC_DATA` doesn't make sense since the purpose of this permission is not to give an external app permission to read nfc data (we don't have that functionality for external apps) but merely to protect the app's exposed components that should not ideally be exposed in the first place. As such we should have one single permission like `PROTECT_FALSELY_EXPOSED_COMPONENTS` and apply it to all such components.

2025-01-09 08:53 UTC, avazirna commented on app/AndroidManifest.xml
> +        android:name="${applicationId}.permission.READ_NFC_DATA"
Makes sense having an umbrella permission for these, so this will be applied to `READ_NFC_DATA`, `WRITE_NFC_DATA`, `DRAW_BOUNDARY_AREA` and `PRINT`

2025-01-09 10:49 UTC, avazirna commented
Applied the same permission to `DataChangeLogsActivity`

2025-01-09 11:00 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +            android:permission="org.commcare.dalvik.permission.UPDATE_TO_LATEST_BUILD"
`RefreshToLatestBuildReceiver` is a internal dev only tool and introducing a permission here will break the underlying scripts. Given it was marked as `exported=false` earlier, is there a good reason change that to `true` now ?

2025-01-09 11:00 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +            android:exported="true"
why do we need to export this activity ? (I don't recall using it in callouts)

2025-01-09 11:56 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:permission="org.commcare.dalvik.permission.UPDATE_TO_LATEST_BUILD"
I might not have enough context here, but my understanding is that this receiver is for external use, its documentation also states that it should respond to requests via `adb`, in that case it needs to be exported.

> Trigger from command line with:
>  *   adb shell am broadcast -a org.commcare.dalvik.api.action.RefreshToLatestBuildAction

Considering that this is for dev use only, what's the usage? To make sure the feature is working as expected?

2025-01-09 11:59 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +            android:permission="org.commcare.dalvik.permission.UPDATE_TO_LATEST_BUILD"
It's a adb command to update the app to latest without interacting with UI and was meant to increase dev efficiency - https://github.com/dimagi/commcare-android/blob/master/scripts/ccc#L63

2025-01-09 12:03 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:exported="true"
It's not, but it's supposed to respond to `ACTION_VIEW` actions, so I think it needs to be exported. I didn't test this though, let me do that.

2025-01-09 12:09 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:exported="true"
Btw from the [Spec](https://docs.google.com/document/d/1LJIaQMoex6SM90gAxJbLRsMw8FC_0FtJLbMbmxGE5dE/edit?tab=t.0), I don't see the reason for this activity to respond o `ACTION_VIEW` actions, can you provide some context here?

2025-01-09 12:09 UTC, shubham1g5 commented on app/AndroidManifest.xml
> +            android:exported="true"
I think that's again because of dev tooling - https://github.com/dimagi/commcare-android/blob/master/scripts/ccc#L217 which I am fine with killing.

2025-01-09 12:14 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:permission="org.commcare.dalvik.permission.UPDATE_TO_LATEST_BUILD"
Deleting this receiver then, thanks

2025-01-10 00:32 UTC, avazirna commented on app/AndroidManifest.xml
> +            android:exported="true"
@shubham1g5 I've reverted the `exported` status of these components, I will kill them or move to a different manifest file in a different PR.

2025-01-10 04:35 UTC, shubham1g5 approved these changes

2025-01-10 04:35 UTC, shubham1g5 commented on app/res/values/strings.xml
> +    <string name="permission_group_internal_action_label">Permission group for CommCare Internal Actions</string>
can we try to simply these strings and make them user-friendly (remove any tech jargain like intents/callouts) as these may be presented to the users.

2025-01-10 07:49 UTC, avazirna commented on app/res/values/strings.xml
> +    <string name="permission_group_internal_action_label">Permission group for CommCare Internal Actions</string>
Done [abe2a90](https://github.com/dimagi/commcare-android/pull/2930/commits/abe2a902dfc8701c9d6e2a61c74fc1203cae328f)

2025-01-10 08:04 UTC, merged